Data:
  value: exposure
T:
  value: 500
img_size:
  value: 64
channels:
  value: 64
time_dim:
  value: 256
lr:
  value: 0.001
num_epochs:
  value: 30
batch_size:
  value: 16
beta_start:
  value: 0.0001
beta_end:
  value: 0.02
ev:
  value: N
testing:
  value: False

