Data:
  value: sprites
T:
  value: 500
img_size:
  value: 16
channels:
  value: 32
time_dim:
  value: 256
lr:
  value: 0.001
num_epochs:
  value: 100
batch_size:
  value: 128
beta_start:
  value: 0.0001
beta_end:
  value: 0.02
ev:
  value: P
testing:
  value: False

