method: bayes
name: 'sweep_config_1'
metric:
  name: val loss
  goal: minimize
parameters:
  lr:
    min: 0.0000001
    max: 0.01
  num_epochs:
    value: 3
  batch_size:
    value: 5
  beta_start:
    value: 0.0001
  beta_end:
    value: 0.02
  ev:
    value: P1
  testing:
    value: True
  T:
    value: 500
  img_size:
    value: 64
  channels:
    value: 32
  time_dim:
    value: 256